version: "1.1"
languages:
  lua:
    classes:
      ISConfigHeadlight:
        extends: ISBaseTimedAction
        constructors:
          - parameters:
              - name: character
                type: IsoPlayer
              - name: part
                type: VehiclePart
              - name: dir
                type: integer
              - name: time
                type: number
        staticFields:
          Type:
            defaultValue: '"ISConfigHeadlight"'
        fields:
          vehicle:
            type: BaseVehicle
          part:
            type: VehiclePart
          dir:
            type: integer
        methods:
          - name: isValid
            return:
              - type: boolean
          - name: update
          - name: start
          - name: stop
          - name: perform
