version: "1.1"
languages:
  lua:
    aliases:
      umbrella.ServerSettingsScreen.Setting:
        - type: umbrella.ServerSettingsScreen.CheckboxSetting
        - type: umbrella.ServerSettingsScreen.EntrySetting
        - type: umbrella.ServerSettingsScreen.EnumSetting
        - type: umbrella.ServerSettingsScreen.StringSetting
    classes:
      ServerSettingsScreen:
        extends: ISPanelJoypad
        constructors:
          - parameters:
              - name: x
                type: number
              - name: y
                type: number
              - name: width
                type: number
              - name: height
                type: number
        staticFields:
          Type:
            defaultValue: '"ServerSettingsScreen"'
          instance:
            type: ServerSettingsScreen
            nullable: true
        fields:
          pageStart:
            type: ISPanelJoypad
          pageNew:
            type: BaseServerSettingsPanel
          pageEdit:
            type: ISPanelJoypad
          pageDuplicate:
            type: BaseServerSettingsPanel
          pageRename:
            type: BaseServerSettingsPanel
          pageDelete:
            type: ISPanelJoypad
          pageSpawnPoints:
            type: ISPanelJoypad
          prevScreen:
            type: CoopOptionsScreen
          initialSelectedSettings:
            type: string
            nullable: true
        methods:
          - name: create
          - name: aboutToShow
          - name: onResolutionChange
            parameters:
              - name: oldw
                type: number
              - name: oldh
                type: number
              - name: neww
                type: number
              - name: newh
                type: number
          - name: onGainJoypadFocus
            parameters:
              - name: joypadData
                type: JoypadData
          - name: getCurrentFocusForController
            return:
              - type: ISUIElement
                nullable: true
          - name: onJoypadBeforeDeactivate
            parameters:
              - name: joypadData
                type: JoypadData
          - name: onResetLua
            parameters:
              - name: reason
                type: string
        staticMethods:
          - name: getSandboxSettingsTable
            return:
              - type: umbrella.ServerSettingsScreen.SettingsPage[]
      BaseServerSettingsPanel:
        extends: ISPanelJoypad
        staticFields:
          Type:
            defaultValue: '"BaseServerSettingsPanel"'
        methods:
          - name: onLoseJoypadFocus
            parameters:
              - name: joypadData
                type: JoypadData
          - name: onJoypadDown
            parameters:
              - name: button
                type: integer
              - name: joypadData
                type: JoypadData
          - name: onJoypadDirUp
            parameters:
              - name: joypadData
                type: JoypadData
          - name: onJoypadDirDown
            parameters:
              - name: joypadData
                type: JoypadData
      SpawnRegionsNameFilePanel:
        extends: ISPanelJoypad
        constructors:
          - parameters:
              - name: x
                type: number
              - name: y
                type: number
              - name: width
                type: number
        staticFields:
          Type:
            defaultValue: '"SpawnRegionsNameFilePanel"'
        fields:
          entryName:
            type: ISTextEntryBox
          entryFile:
            type: ISTextEntryBox
          joypadButtons:
            type: ISButton[]
          selectedItem:
            type: umbrella.ServerSettingsScreen.SpawnRegionItem
            nullable: true
          joypadFocused:
            type: boolean
            nullable: true
        methods:
          - name: createChildren
          - name: render
          - name: onNameEntered
          - name: onFileEntered
          - name: setJoypadFocused
            parameters:
              - name: focused
              - name: joypadData
                type: JoypadData
          - name: onGainJoypadFocus
            parameters:
              - name: joypadData
                type: JoypadData
          - name: onLoseJoypadFocus
            parameters:
              - name: joypadData
                type: JoypadData
          - name: onJoypadDown
            parameters:
              - name: button
                type: integer
              - name: joypadData
                type: JoypadData
          - name: onJoypadDownInParent
            parameters:
              - name: button
                type: ISButton
              - name: joypadData
                type: JoypadData
            return:
              - type: boolean
      DefaultServerSettings:
        methods:
          - name: insertUnique
            parameters:
              - name: _table
                type: table
              - name: value
                type: unknown
          - name: setServerOptionValue
            parameters:
              - name: settings
                type: ServerSettings
              - name: option
                type: string
              - name: _table
                type: table
          - name: setDefaultsFromSingleplayer
            parameters:
              - name: settings
                type: ServerSettings
      Page3.ChooseModsWindow:
        extends: ISPanelJoypad
        local: true
        constructors:
          - parameters:
              - name: x
                type: number
              - name: y
                type: number
              - name: width
                type: number
              - name: height
                type: number
        staticFields:
          Type:
            defaultValue: '"Page3.ChooseModsWindow"'
        fields:
          listbox:
            type: ISScrollingListBox
          buttonCancel:
            type: ISButton
          buttonMods:
            type: ISButton
          buttonAccept:
            type: ISButton
          modInfoByID:
            type: table<string, ChooseGameInfo.Mod>
        methods:
          - name: create
          - name: onGainJoypadFocus
            parameters:
              - name: joypadData
                type: JoypadData
          - name: onButtonCancel
          - name: onButtonMods
          - name: onButtonNext
          - name: aboutToShow
          - name: addModToList
            parameters:
              - name: modID
                type: string
          - name: render
      umbrella.ServerSettingsScreen.SettingsPage:
        fields:
          name:
            type: string
          title:
            type: string
            nullable: true
          settings:
            type: umbrella.ServerSettingsScreen.Setting[]
          steamOnly:
            type: boolean
            nullable: true
          customui:
            type: ISUIElement
            nullable: true
      umbrella.ServerSettingsScreen.BaseSetting:
        fields:
          name:
            type: string
          translatedName:
            type: string
          tooltip:
            type: string
            nullable: true
          type:
            type: string
      umbrella.ServerSettingsScreen.CheckboxSetting:
        fields:
          type:
            type: '"checkbox"'
          default:
            type: boolean
      umbrella.ServerSettingsScreen.EntrySetting:
        fields:
          type:
            type: '"entry"'
          text:
            type: string
          onlyNumbers:
            type: boolean
            nullable: true
      umbrella.ServerSettingsScreen.EnumSetting:
        fields:
          type:
            type: '"enum"'
          values:
            type: string[]
          default:
            type: integer
      umbrella.ServerSettingsScreen.StringSetting:
        fields:
          type:
            type: '"string" | "text"'
          text:
            type: string
      umbrella.ServerSettingsScreen.SpawnRegionItem:
        fields:
          name:
            type: string
          file:
            type: string
