version: "1.1"
languages:
  lua:
    classes:
      biome_map_config:
        staticFields:
          "[1]": {}
          "[2]": {}
          "[3]": {}
          "[4]": {}
          "[5]": {}
          "[6]": {}
          "[7]": {}
          "[8]": {}
          "[9]": {}
          "[10]": {}
          "[11]": {}
          "[12]": {}
          "[13]": {}
          "[14]": {}
          "[15]": {}
          "[16]": {}
          "[17]": {}
          "[18]": {}
          "[19]": {}
