version: "1.1"
languages:
  lua:
    classes:
      ISInventoryMenuElements:
        staticMethods:
          - name: ContextRadio
            return:
              - type: InvContextRadio
      InvContextRadio:
        extends: ISMenuElement
        local: true
        fields:
          invMenu:
            type: ISMenuContextInventory
        staticMethods:
          - name: init
          - name: createMenu
            parameters:
              - name: _item
                type: InventoryItem
          - name: openPanel
            parameters:
              - name: _p
                type: ISMenuContextInventory
              - name: _item
                type: InventoryItem
