version: "1.1"
languages:
  lua:
    classes:
      ISInventoryMenuElements:
        staticMethods:
          - name: ContextMovable
            return:
              - type: InvContextMovable
      InvContextMovable:
        extends: ISMenuElement
        local: true
        fields:
          invMenu: {}
        staticMethods:
          - name: init
          - name: createMenu
            parameters:
              - name: _item
          - name: openMovableCursor
            parameters:
              - name: _p
              - name: _item
