version: "1.1"
languages:
  lua:
    classes:
      ISInventoryMenuElements:
        staticMethods:
          - name: ContextMedia
            return:
              - type: InvContextMedia
      InvContextMedia:
        extends: ISMenuElement
        local: true
        fields:
          invMenu:
            type: ISMenuContextInventory
        staticMethods:
          - name: init
          - name: createMenu
            parameters:
              - name: _item
                type: InventoryItem
          - name: openMediaInfo
            parameters:
              - name: _p
                type: ISMenuContextInventory
              - name: _item
                type: InventoryItem
              - name: _text
                type: string
          - name: changeRecording
            parameters:
              - name: _p
                type: ISMenuContextInventory
              - name: _item
                type: InventoryItem
              - name: _other
                type: MediaData
                nullable: true
