version: "1.1"
languages:
  lua:
    classes:
      ISInventoryMenuElements:
        staticMethods:
          - name: ContextRadio
            return:
              - type: InvContextRadio
      InvContextRadio:
        extends: ISMenuElement
        local: true
        fields:
          invMenu: {}
        staticMethods:
          - name: init
          - name: createMenu
            parameters:
              - name: _item
          - name: openPanel
            parameters:
              - name: _p
              - name: _item
