version: "1.1"
languages:
  lua:
    classes:
      ISInventoryMenuElements:
        staticMethods:
          - name: ContextFluidContainer
            return:
              - type: InvContextFluidContainer
      InvContextFluidContainer:
        extends: ISMenuElement
        local: true
        fields:
          invMenu:
            type: ISMenuContextInventory
        staticMethods:
          - name: init
          - name: createMenu
            parameters:
              - name: _item
                type: InventoryItem
          - name: addDebugFluid
            parameters:
              - name: _p
                type: ISMenuContextInventory
              - name: cont
                type: FluidContainer
              - name: fluid
                type: string
          - name: transferFluids
            parameters:
              - name: _p
                type: ISMenuContextInventory
              - name: _container
                type: FluidContainer
          - name: showInfo
            parameters:
              - name: _p
                type: ISMenuContextInventory
              - name: _container
                type: FluidContainer
          - name: emptyFluidContainer
            parameters:
              - name: _p
                type: ISMenuContextInventory
              - name: _container
                type: FluidContainer
          - name: joypadHideInventoryAndLoot
            parameters:
              - name: _p
                type: InvContextFluidContainer
