version: "1.1"
languages:
  lua:
    classes:
      ISConfirmMonitorSettingsDialog:
        extends: ISModalDialog
        constructors:
          - parameters:
              - name: x
                type: number
              - name: y
                type: number
              - name: width
                type: number
              - name: height
                type: number
              - name: callback
                type: umbrella.ISButton.OnClick
                nullable: true
              - name: param1
                type: unknown
                nullable: true
              - name: param2
                type: unknown
                nullable: true
        staticFields:
          Type:
            defaultValue: '"ISConfirmMonitorSettings"'
        fields:
          startTime:
            type: number
        methods:
          - name: initialise
          - name: update
          - name: render
