version: "1.1"
languages:
  lua:
    classes:
      ISUIEmoteConfig:
        extends: ISCollapsableWindow
        constructors:
          - parameters:
              - name: x
                type: number
              - name: y
                type: number
              - name: character
        staticFields:
          Type:
            defaultValue: '"ISUIEmoteConfig"'
        fields:
          saveBtn:
            type: ISButton
          close:
            type: ISButton
          categoryLbl:
            type: ISLabel
          categoryCB:
            type: ISComboBox
          emoteLbl:
            type: ISLabel
          emoteCB:
            type: ISComboBox
          addNewEmoteBtn:
            type: ISButton
          remoteEmoteBtn:
            type: ISButton
          playerNum:
            type: integer
          chr: {}
        methods:
          - name: createChildren
          - name: close
          - name: selectCategory
            parameters:
              - name: combo
          - name: prerender
          - name: render
          - name: writeToFile
          - name: readFile
