version: "1.1"
languages:
  lua:
    classes:
      HitReactionSettingsPanel:
        extends: ISDebugSubPanelBase
        constructors:
          - parameters:
              - name: x
                type: number
              - name: y
                type: number
              - name: width
                type: number
              - name: height
                type: number
              - name: doStencil
        staticFields:
          Type:
            defaultValue: '"HitReactionSettingsPanel"'
        fields:
          allOptions:
            type: table
          floats:
            type: table
          bools:
            type: table
        methods:
          - name: initialise
          - name: createChildren
          - name: onClick
            parameters:
              - name: _button
                type: ISButton
          - name: addBoolOption
            parameters:
              - name: _id
              - name: _bool
              - name: _x
                type: number
              - name: _y
                type: number
              - name: _w
                type: number
            return:
              - type: number
          - name: addFloatOption
            parameters:
              - name: _id
              - name: _float
              - name: _x
                type: number
              - name: _y
                type: number
              - name: _w
                type: number
            return:
              - type: number
          - name: prerender
          - name: onSliderChange
            parameters:
              - name: _newval
              - name: _slider
          - name: onTicked
            parameters:
              - name: _index
              - name: _selected
              - name: _arg1
                type: unknown
              - name: _arg2
                type: unknown
              - name: _tickbox
          - name: onTickedValue
            parameters:
              - name: _index
              - name: _selected
              - name: _arg1
                type: unknown
              - name: _arg2
                type: unknown
              - name: _tickbox
          - name: update
